#ifndef BLACK_LABEL_THREAD_POOL_DYNAMIC_INTERFACE_HPP
#define BLACK_LABEL_THREAD_POOL_DYNAMIC_INTERFACE_HPP



#define BLACK_LABEL_THREAD_POOL_DYNAMIC_INTERFACE
#include "black_label/thread_pool.hpp"



#endif
