# Boost
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
find_package(Boost 1.50.0 QUIET REQUIRED date_time system chrono thread)
list(APPEND BlackLabel_DEPENDENCIES_THREAD_POOL_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})
list(APPEND BlackLabel_DEPENDENCIES_THREAD_POOL_LIBRARIES 
	${Boost_DATE_TIME_LIBRARIES}
	${Boost_SYSTEM_LIBRARIES}
	${Boost_CHRONO_LIBRARIES}
	${Boost_THREAD_LIBRARIES})
