# Boost
find_package(Boost ${COMMON_BOOST_VERSION} QUIET REQUIRED)
list(APPEND BlackLabel_DEPENDENCIES_COMMON_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})

# GLM
find_package(GLM REQUIRED)
list(APPEND BlackLabel_DEPENDENCIES_COMMON_INCLUDE_DIRS ${GLM_INCLUDE_DIR})

# TBB
find_package(TBB)
list(APPEND BlackLabel_DEPENDENCIES_COMMON_INCLUDE_DIRS ${TBB_INCLUDE_DIR})
list(APPEND BlackLabel_DEPENDENCIES_COMMON_LIBRARIES ${TBB_LIBRARY})
